packages:
  - .

allowBuilds:
  esbuild: true
  puppeteer: true
  sharp: true
  workerd: true

autoInstallPeers: true
strictPeerDependencies: false

overrides:
  postcss: ^8.5.10
  undici: ^7.29.1

packageImportMethod: clone-or-copy
